version: '3.9'

services:
  db:
    restart: always
    image: postgres:16.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6380"
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    tty: true
    stdin_open: true